- name: "variables at play-level"
  hosts: "local"
  connection: "local"
  vars:
    role: "DevOps with AWS"
    location: "Hyderabad"
    company: "Infosys"
  tasks:
  - name: "printing the play-level variables and this is task"
    ansible.builtin.debug:
      msg: "Role is {{ role }} Location is {{ location }} and company is {{ company }}"


