- name: "Task-level variables"
  hosts: "local"
  connection: "local"
  become: yes
  vars:
    role: "DevOps with AWS"
    location: "Hyderabad"
    company: "Salesforce"
  tasks:
  - name: "printing task level varaibles this is task under the play"
    vars:
      role: "DevOps with AWS"
      location: "Hyderabad"
      company: "Infosys"
    ansible.builtin.debug:
      msg: "Role is {{ role }} location is {{ location }} and company is {{ company }}"
    
