- name: "varaibles from the file"
  hosts: "local"
  connection: "local"
  become: yes
  vars_files:
  - info.yaml
  tasks:
  - name: "printing variables from the file"
    ansible.builtin.debug:
      msg: "Role is {{ role }} location is {{ location }} and company is {{ company }}"  

