- name: "checking varibles from prompt"
  hosts: "local"
  connection: "local"
  become: "yes"
  vars_prompt:
    - name: role
      prompt: What is your role?
      private: true

    - name: location
      prompt: What is your location?
      private: false
  tasks:
  - name: "printing variables from prompt this is task under play"
    ansible.builtin.debug:
      msg: "Role is {{ role }} and location is {{ location }}"