- name: "varibales from prompt"
  hosts: "local"
  connection: "local"
  vars_prompt:
    - name: username
      prompt: What is your username?
      private: false

    - name: password
      prompt: What is your password?
      private: true
  tasks:
    - name: "checking prompt variables"
      ansible.builtin.debug:
        msg: "username is {{ username }}, and password is {{ password }}"
        