- name: "checking varables from inventory file"
  hosts: "local"
  connection: "local"
  tasks:
  - name: "printing the varaibles from inventory file this is task under the play"
    ansible.builtin.debug:
      msg: "role is {{ role }} and location is {{ location }}"