- name: "variable preferences"
  hosts: "local"
  connection: "local"
  become: "yes"
  # vars:
  #   location: "from play-level"
  # vars_files:
  # - info.yaml
  # vars_prompt:
  #   - name: location
  #     prompt: What is your location?
  #     private: true
  tasks:
  - name: "printing variable preferences this task from play"
    # vars:
    #   location: "from task-level"
    ansible.builtin.debug:
      msg: "location is {{ location }}"

    
