- name: "checking the condition"
  hosts: "local"
  connection: "local"
  become: yes
  tasks:
  - name: "printing the condition this is task under play"
    vars:
      number: 6
    ansible.builtin.debug:
      msg: " {{ number }} is lessthan 10"
    when: number < 10 
