- name: functions
  hosts: "local"
  connection: "local"
  become: yes
  vars:
    technologies: AWS ,java ,mysql #string
    name: "Bharath kumar G"
    gmail: "bharath@gmail.com"
    phno: "9876543210"

    technologiess:
    - java
    - AWS
    - just
    tags:
      Application: payment
      Environment: dev

    listtags: #listDIC
    - key: Application
      value: payment
    - key: Environment
      value: dev
  tasks:
  - name: "default variables"
    ansible.builtin.debug:
     msg: "{{ dakati | default('mahesh') }}"  

  - name: "split string to list"
    ansible.builtin.debug:
      msg: "{{ technologies | split(',') }}"   

  - name: "convert dic to list"
    ansible.builtin.debug:
      msg: "{{ tags | dict2items }}" 

  - name: "list to dic" 
    ansible.builtin.debug:
      msg: "{{ listtags | items2dict }}"


  - name: grep for root
    #ansible.builtin.command: cat /etc/passwd | grep root
    ansible.builtin.shell: cat /etc/passwd | grep root
    register: command_output

  - name: "print the command_output variable"
    ansible.builtin.debug:
      msg: {{ command_output }}




